
FROM samber/github-actions-runner:latest

USER root

RUN cd /tmp \
    && wget https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz \
    && tar -xvf go1.13.3.linux-amd64.tar.gz \
    && mv go /usr/local/src \
    && ln -s /usr/local/src/go/bin/go /usr/local/bin/ \
    && apt-get update \
    && apt-get install -y -q build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER runner
